# Site settings
title: "Helle AS - Rørleggere på Bømlo"
email: "post@helleas.no"
description: > # this means to ignore newlines until "baseurl:"
    "Helle AS er din lokale rørlegger på Bømlo. Vi setter kort responstid, fleksibilitet, personlig service og kundeforhold i høysetet. Rørleggeren du stoler på!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://helleas.no" # the base hostname & protocol for your site
author: "Anders Helle"

plugins:
  - jekyll-sitemap

twitter_username:
github_username:

# Build settings
markdown: kramdown
