# Site settings
title: "Pro-Rør Bømlo"
email: "post@pro-ror.no"
# ander.helle@pro-ror.no
description: > # this means to ignore newlines until "baseurl:"
    Velkommen til Pro-Rør Bømlo. Din lokale rørlegger!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "pro-ror.no" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
